### ISSUE TITLE
need use "tm ms host1 host2"

### ISSUE THREAD

**Issue by jolinux** [Ganneff/tm#62]
Can I use tm with multi host connect  by command line ?

Like  

tm ms user@192.168.0.1 user2@192.168.0.2

**Comment by Ganneff** [comment]
Yes, sure. Its one of the ways we use it most, actually, aside from pre-existing configs.
The longest I opened with this was something around 400 hosts (generated commandline, and it took the machine quite a while to handle all the window creation in tmux, but it works).
